// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HomeModuleScssNamespace {
  export interface IHomeModuleScss {
    home: string;
  }
}

declare const HomeModuleScssModule: HomeModuleScssNamespace.IHomeModuleScss;

export = HomeModuleScssModule;
