// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace StyleScssNamespace {
  export interface IStyleScss {
    home: string;
  }
}

declare const StyleScssModule: StyleScssNamespace.IStyleScss;

export = StyleScssModule;
