// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace ProfileModuleScssNamespace {
  export interface IProfileModuleScss {
    profile: string;
  }
}

declare const ProfileModuleScssModule: ProfileModuleScssNamespace.IProfileModuleScss;

export = ProfileModuleScssModule;
