// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace HeaderModuleScssNamespace {
  export interface IHeaderModuleScss {
    active: string;
    header: string;
  }
}

declare const HeaderModuleScssModule: HeaderModuleScssNamespace.IHeaderModuleScss;

export = HeaderModuleScssModule;
