// This file is automatically generated from your CSS. Any edits will be overwritten.
declare namespace NotFoundModuleScssNamespace {
  export interface INotFoundModuleScss {
    notfound: string;
  }
}

declare const NotFoundModuleScssModule: NotFoundModuleScssNamespace.INotFoundModuleScss;

export = NotFoundModuleScssModule;
